
spring:
  application:
    name: tw-mall
  cloud:
    consul:
      enabled: true
      host: ${CONSUL_HOST:127.0.0.1}
      port: 8500
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database: mysql

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tw_mall
    username: root
    password:
server:
  port: 8081

jwt:
  secret: mySecret

